sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t  laxman13/docker-multicon -test  -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true laxman13/docker-multicon -test npm test

after_success:
  - docker build -t laxman13/multi-client ./client
  - docker build -t laxman13/multi-nginx ./nginx
  - docker build -t laxman13/multi-server ./server
  - docker build -t laxman13/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push laxman13/multi-client
  - docker push laxman13/multi-nginx
  - docker push laxman13/multi-server
  - docker push laxman13/multi-worker
